stages:
  - prepare
  - build_and_test
  - notify

# If you are looking for a place where to add 'UNITY_LICENSE_FILE' and other secrets, please visit your project's gitlab page:
# settings > CI/CD > Variables instead
variables:
  BUILD_NAME: medical-training
  UNITY_ACTIVATION_FILE: ./unity3d.alf
  VARIABLES_FILE: ./.variables.txt
  IMAGE: unityci/editor # https://hub.docker.com/r/unityci/editor
  IMAGE_VERSION: 3 # This will automatically use latest v1.x.x, see https://github.com/game-ci/docker/releases
  UNITY_DIR: $CI_PROJECT_DIR # this needs to be an absolute path. Defaults to the root of your tree.
  # You can expose this in Unity via Application.version
  VERSION_NUMBER_VAR: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_JOB_ID
  VERSION_BUILD_VAR: $CI_PIPELINE_IID
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  ACCESS_TOKENS_PATH: $CI_PROJECT_DIR/../$CI_PROJECT_NAME.tmp/ACCESS_TOKENS

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

get-unity-version:
  image: alpine
  stage: prepare
  interruptible: true
  resource_group: production
  variables:
    GIT_DEPTH: 1
  script:
    - echo UNITY_VERSION=$(cat $UNITY_DIR/ProjectSettings/ProjectVersion.txt | grep "m_EditorVersion:.*" | awk '{ print $2}') | tee prepare.env
  artifacts:
    reports:
      dotenv: prepare.env
    expire_in: 1 min

.unity_before_script: &unity_before_script
  before_script:
    - chmod +x ./ci/before_script.sh && ./ci/before_script.sh
    - chmod +x ./ci/DependencyURLRewriter.sh && ./ci/DependencyURLRewriter.sh $ACCESS_TOKENS_PATH $UNITY_DIR/Packages/manifest.json
  needs:
    - job: get-unity-version
      artifacts: true

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/

.license: &license
  rules:
    - if: '$UNITY_LICENSE != null'
      when: always

.unity_defaults: &unity_defaults
  <<:
    - *unity_before_script
    - *cache
    - *license

# run this job when you need to request a license
# you may need to follow activation steps from documentation
get-activation-file:
  <<: *unity_before_script
  rules:
    - if: '$UNITY_LICENSE == null'
      when: manual
  stage: prepare
  interruptible: true
  resource_group: production
  script:
    - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
  artifacts:
    paths:
      - $UNITY_ACTIVATION_FILE
    expire_in: 10 min # Expiring this as artifacts may contain sensitive data and should not be kept public

.test: &test
  stage: build_and_test
  interruptible: true
  resource_group: production
  <<: *unity_defaults
  script:
    - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    when: always
    expire_in: 1 min
  # https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/83
  # you may need to remove or replace these to fit your need if you are using your own runners
  tags:
    - gitlab-org
  coverage: /<Linecoverage>(.*?)</Linecoverage>/

.build: &build
  stage: build_and_test
  interruptible: true
  resource_group: production
  <<: *unity_defaults
  script:
    - echo "export ARTIFACT_DOWNLOAD_URL=$CI_JOB_URL/artifacts/download" > $VARIABLES_FILE
    - echo "Build based on $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA" > ./README.md
    - chmod +x ./ci/build.sh && ./ci/build.sh
  artifacts:
    name: "Medical_TrAining_artifacts"
    paths:
      - $VARIABLES_FILE
      - ./README.md
      - $UNITY_DIR/Builds/
    expire_in: 1 min
  # https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/83
  # you may need to remove or replace these to fit your need if you are using your own runners
  tags:
    - gitlab-org

build-StandaloneWindows64:
  <<: *build
  image: $IMAGE:$UNITY_VERSION-windows-mono-$IMAGE_VERSION
  variables:
    BUILD_TARGET: StandaloneWindows64

notify_mattermost:
  image: ruby:2.7
  stage: notify
  interruptible: true
  resource_group: production
  needs: ['build-StandaloneWindows64']
  script:
    - source $VARIABLES_FILE
    - chmod +x ./ci/mm_notify.sh && ./ci/mm_notify.sh
  rules:
    - when: on_success

# MergeRequest Pipeline Workflow
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/MergeRequest-Pipelines.gitlab-ci.yml
workflow:
  rules:    
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "web"
